# Generated by Django 3.2.7 on 2021-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='Cantidad',
            new_name='cantidad',
        ),
    ]
