# Generated by Django 3.2.7 on 2021-12-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades de Empleados'},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='Habilidades',
            new_name='habilidades',
        ),
    ]
