# Generated by Django 3.2.7 on 2022-02-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20211207_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Personal de la empresa', 'verbose_name_plural': 'Datos Empleado'},
        ),
    ]
